### ISSUE TITLE
Infografía Libreria 

### ISSUE THREAD

**Issue by NayeliMoraless** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-NayeliMoraless#1]
[Infografia_librerias.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-NayeliMoraless/files/14606569/Infografia_librerias.pdf)

**Comment by ElisabetRD** [comment]
19.5% falta créditos

**Comment by josealfredo79** [comment]
Bien echo y revisado...
